name: Try security Scanning 
on: 
  push: 
    branches: [security*]
  workflow_dispatch: 

jobs:
  rstudio_scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Grep for common token patterns
        id: pattern_scan
        run: |
          egrep -R -f config/grep.conf *
          echo "::set-output name=exit_code::$?"
      
      # Exit code from Grep: 0 => Match found; 1 => No match found; 2 => Error in matching
      - name: "Outputting last exit Code"
        if: ${{ steps.pattern_scan.outputs.exit_code }} == 0
        run: |
          echo "Matches were found, please view log output and resolve issues"
        
      