name: Try security Scanning 
on: 
  push: 
    branches: [security*]
  workflow_dispatch: 

jobs:
  rstudio_scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # We have an exclude files to exclude certain files in the grep
      - name: Grep for common token patterns
        id: pattern_scan
        run: |
          echo "::set-output name=grep_count::$(egrep -R -f config/grep.conf * $(for i in `cat config/exclude_from_grep.conf`; do  echo --exclude=$i; done) | wc -l)"
     
      - name: "Matches were found"
        if: ${{ steps.pattern_scan.outputs.grep_count }} != 0
        run: |
          echo 
          echo "${{ steps.pattern_scan.outputs.grep_count }} Matches were found, please view log output and resolve issues"
          exit 1
        
      