name: Testing mechanism for retrieving changed files
on: 
  push: 
    branches: [main]
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: retrieve last deployed hash for diff
        id: retrieve_last_hash
        run: |
          echo "::set-output name=last_hash::$(cat .doesnotexist 2>/dev/null || echo $(git hash-object -t tree /dev/null))"

      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ steps.retrieve_last_hash.outputs.last_hash }} $GITHUB_SHA | xargs)"

      - name: echo the output
        run: | 
          for file in ${{ steps.getfile.outputs.files }}
          do
            echo "Current file is: $file";
          done; 