name: Testing mechanism for retrieving changed files
on: 
  push: 
    branches: [main]
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ GITHUB_SHA }} | xargs)"

      - name: echo the output
        run: | 
          echo ${{ steps.getfile.outputs.files }}